### ISSUE TITLE
Screen Resolution Config

### ISSUE THREAD

**Issue by danpillay87** [swehner/foos#21]
Hi guys - awesome work here - whats the bes way to debug on my install python3 foos.py is just hitting me with a whitescreen after Run GUI makes it to the console.

Is there any additional config I should be doing? Not sure if I needed to set up the league system in advance tbh as I havn't seen the GUI.

any help appreciated :) happy to do a full noob write up once I have this nailed...

**Comment by swehner** [comment]
Hi,

What platform are you trying to run it on and with what version of Pi3d?
Can you also please post the whole output on the console? Maybe we can find some hints there.
If you're running on the RaspberryPi, have you checked this out: https://pi3d.github.io/html/FAQ.html#white-screen 

If it is related to memory issues on the RaspberryPi you might want to check the output of vcdgb reloc  while it is running, to see how much memory is free/being used.
Let me know if you have some more information to go on and we'll see if we can help somehow!
Thanks!

**Comment by ErnieTheTech** [comment]
Hey Dan, I was having the white screen issue on my TV at work and one at my home but my 2nd tv at home loaded full screen. 
I think has to do with default resolution. You should be able to get it running slightly on any tv doing -s 3 which will display in a tiny portion of the screen.
Is there a default resolution in a config somewhere?
Unfortunately once the GUI loads, I can't do anything with a keyboard.
On an unrelated note, I was getting a syntax error running a copy of the sample config.py file.
It points out maxBytes in the code and the GUI won't load unless I comment the line out and save the config file.
Thanks for all your help.

**Comment by dpaneda** [comment]
Fixed syntax error in the sample config at 504c3b5d4d26ebe8ef0cc351814b0273349b776c
I'm not sure about the default resolution, @swehner is our gui expert :D.
About the keyboard problem, did you try the control keys specified on the Readme?

**Comment by swehner** [comment]
Thanks for fixing this, @dpaneda :)
So - regarding the resolution: by default it'll try to use the whole display and scale the camera accordingly.
Like @ErnieTheTech said, if you specify a scaling factor on the command line the window size will be forced to <1920/sf>x<1080/sf>.

I think the keyboard commands specified in the README work only when running in X11.
So if you run it on the Raspberry Pi directly from the command line this doesn't work I think.
I'll double check it - but the io_keyboard plugin is specific to X11 and is only loaded if Pi3D detects it's running under X.
I'll take a look to see if we can get this running also when running without X.

If you can ssh into the RaspberryPi you can use the scripts in debug to trigger events https://github.com/swehner/foos/tree/master/debug - so this can simulate inputs from the serial port.

**Comment by danpillay87** [comment]
thanks guys - I tried both of these - I just removed any raspbian related GUI stuff from the pi which seems to have resolve my whitescreen issue - have also managed to resize the foos gui on my TV so I'm getting ish better results but yeah @ErnieTheTech the -s3 command would be pretty helpful.

**Comment by ErnieTheTech** [comment]
Thanks @dpaneda , that worked great.
@swehner , is there a way I can set the exact resolution? Its running OK on a monitor and one TV but its not perfect (black line where the time is). I would like to be able to set the resolution if possible.
I will check out the keyboard later today.

**Comment by ErnieTheTech** [comment]
@danpillay87 , what did you remove? What did you do to resize the GUI?

**Comment by swehner** [comment]
@ErnieTheTech Nope - at the moment it's not possible to set the exact resolution without changing the code. If you want to try you can try to play around with the size in  https://github.com/swehner/foos/blob/master/foos/ui/ui.py#L263
What's the resolution/aspect ratio of your TV you're trying to set up? Can you also please tell me what python3 foos.py (without the -s argument) prints when running?
It will print the display size detected by pi3d

So to explain a bit more: the GUI is layed for an aspect ratio of 16:9 (all positions are hardcoded on a 1920x1080 screen) and scaled if the window is to be drawn with a different size.
By default it will try to use the full screen size - if your TV has a different aspect ratio it's very likely you'll see black bars on top or bottom - might that be your issue?

**Comment by ErnieTheTech** [comment]
So on a standard monitor, SSH from another computer without -s it sets the size to 1366x768@25. You can see the black bars.
When -s 3 it sets to 640x360@25 and everything seems to display correct, only smaller.
Pictures below:

https://1drv.ms/i/s!Ajbtyf8_31eygoVX3WK3hkW18B_oDg

https://1drv.ms/i/s!Ajbtyf8_31eygoVYtlk9ck01QB0lpw

**Comment by swehner** [comment]
Thanks for the screenshots! Very helpful and quite different from what I thought it was.
Because the size is ok, it's just that it's not drawing the text correctly.
I'm suspecting a GPU memory issue here - I think I had these kinds of issues when trying to load too much into the GPU memory (e.g. too many images at the same time)
Can you verify what your GPU memory setting is? And what your free memory for GPU is?

You should get the amount of free memory doing sudo vcdbg reloc - this will show all reserved blocks and also what memory is free still.
I'd recommend raising your assigned memory for the GPU (I think at least 128MB if not more) - you can use raspi-config for that.
Let me know if that changes anything!

**Comment by ErnieTheTech** [comment]
@swehner, it was set to 64 so I changed it to 128 and 256. Check the image below. Seems there are now 5 black dots near the the bottom center. I rebooted so that several different images would boot up but same result. 
*Please note that I dont have anything connected or configured at this time. Just the Pi and all the required installs.
Also, for the camera-can I use any compatible USB camera or must it be one connected via ribbon and board?
A big thank you for helping me out in the project. I hope you don't mind all the questions. I have a few weeks off from school and wanted to complete this before the semester.

Photo:
https://1drv.ms/i/s!Ajbtyf8_31eygoVaAIdyIoPKwl5zGw

**Comment by swehner** [comment]
Awesome! The black dots are actually an on screen display for the LED buttons we have on the box.
So that is completely normal - if you use the debug script to send a goal you should actually see them flashing...
You can disable them setting onscreen_leds_enabled to False in your config.py. See here: https://github.com/swehner/foos/blob/master/config.py.sample#L1
Verify that it's written correctly and that should be enough :)

Re: the camera - nope, we don't support a USB camera - only the RaspberryPi camera.
Most USB cameras don't do more than 30fps with isn't enough for slow-motion replays and I'm not sure how well supported they are...
Right now everything's tailored to raspivid and how the video recording works there. 
So generally, getting a USB camera to do the replays could be doable but it'll be a lot more work, and we're definitely not supporting it.

**Comment by swehner** [comment]
BTW: If the ribbon cable length is an issue for you we can recommend this: https://www.tindie.com/products/freto/pi-camera-hdmi-cable-extension/
It's awesome!

**Comment by ErnieTheTech** [comment]
Awesome, perfect! Time to order a few items. I just got my arduino in today so I will be playing with next couple of days. Hopefully I can leave yall alone for now :)

Thanks again for all the help.

**Comment by swehner** [comment]
No problem - these are quite a few things we weren't aware of. I'll try to see if we can either include them somehow in the program itself (check for enough GPU memory) oor at least document them in the README.
Have fun with the Arduino :)

@danpillay87 have you checked if your problems were also related to the GPU Ram settings?

**Comment by ErnieTheTech** [comment]
@swehner . So playing with the arduino is pretty simple. The kit I bought came with buttons to play with. I have been able to communicate with the Pi using simple push button scripts and works fine.
How can I play with the push button config in foos? I had to set the usb port when running button scripts so wont I need to set that in foos?

**Comment by swehner** [comment]
Foos will try to open a serial connection on any of the /dev/ttyACM* or /dev/ttyUSB* ports.
See here for connection params: https://github.com/swehner/foos/blob/master/plugins/io_serial.py#L66
Our arduino setup basically writes strings for btn up/down events and goal events. You can see them both here: https://github.com/swehner/foos/blob/master/plugins/arduino.py the raspberry pi side and in the arduino code file here: https://github.com/swehner/foos/blob/master/foos_arduino/foos_arduino.ino.
Don't forget to add the io_serial in config.py pluing list. Have fun :D

**Comment by ErnieTheTech** [comment]
@swehner Worked great after I added io_serial to config. 
I am getting this from SSH but everything loads and seems to play fine:

Traceback (most recent call last):
  File "/home/pi/Desktop/foos/plugins/io_serial.py", line 38, in reader_thread
    line = line.decode('ascii').strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)

**Sorry if this is simple fix but I am a Network admin and only know a little about code**

**Comment by danpillay87** [comment]
hi @ErnieTheTech having a little trouble with my arduino set-up don't suppose you have anything you could share to help me on my way? The images on the readme are a bit tricky and I want to make sure I've understood the schematic and the useage of io_serial correctly.

Cheers

**Comment by swehner** [comment]
For the schematic you can also check the fritzing file: https://github.com/swehner/foos/blob/master/doc/foos_arduino.fzz
Maybe that it easier to check than the images.

**Comment by danpillay87** [comment]
cheers swehner - trying it just with buttons and skipping the sensors for the minute to try and isolate the prob. Don't suppose there are any forced commands I can try in debugging to check the arduino setup is okay that people know of? I'm reading it on ttyUSB001 just fine so I'm assuming it's all good but the constant short goal trigger is puzzling me :/

**Comment by swehner** [comment]
I'm gonna go ahead and close this - I think the original issue was addressed and we're talking about the arduino issues in #33
