### ISSUE TITLE
color block

### ISSUE THREAD

**Issue by ErnieTheTech** [swehner/foos#30]
![img_20160803_210003](https://cloud.githubusercontent.com/assets/20694528/17387201/789593d0-59bf-11e6-9d92-e2f828bd2ad5.jpg)

Hey everyone, replay and buttons work great. I am waiting on the IR to get here on Monday.
In the meantime, can you tell me what you think the color block is?

Also, when a goal is scored...right before and right after the replay video, you can see the terminal for a few seconds---is that normal?

Thanks in advance
Running GPU at 256

**Comment by dpaneda** [comment]
The rainbow icon indicates under-voltage on the raspberry. We also face that problem on our installation. You should try to find another usb charger with a higher voltage to fix that. 

We also see the "flickering" problem showing the terminal output on the replays, but in our case it gets solved after some time. I guess that is because the terminal enter power safe mode or something like that. That being said, it would be cool to have that problem fixed, I'm not sure if that is a problem on our software or some kind of bug on pi3d.

**Comment by swehner** [comment]
Hi,

So all things are displayed in dispmanx layers on the raspberry in the following order:
* Video
* UI
When playing a video, the UI background is set to transparent, so the video underneath is visible.
And for a short time the console shows through.
As @dpaneda said, after some time the console goes to black, so that shouldn't be an issue...

Regarding the power supply I think you should go with a 2 amp rating at least - we started out with the recommended 1 amp and it wasn't enough.

**Comment by ErnieTheTech** [comment]
@dpaneda Thank you for responding. You are most certainly correct about the power. When I tested it at home it was being powered by a Roku USB port but when I got to work it was powered with a stand alone power block and cable---issue resolved.

And yes, when I test it after it has been loaded for a while there is no more terminal displayed

Thanks again guys
