### ISSUE TITLE
IR Barrier works not correctly 

### ISSUE THREAD

**Issue by LukeSeinVadder** [swehner/foos#58]
Hello there,

I have a little new problem, maybe you can help me. 
Yesterday we installed the hole project in the tablekicker. At the beginning it all looks wonderful.
We installed the IR Barrier and tested it with the ball 200 times :), when the kickertable was open with normal light evironment. 
Then we closed the table and start playing /  the IR Barrier only works in the dark table, when the ball runs directly in front of the IR LED. When the ball runs in the middle auf the barrier nothing happens....
We have no white ground in the table , it is wood-optic.
The IR LED is installed like yours in the little hole.  

min_goal_usecs parameter is 100

**Comment by swehner** [comment]
Sorry for the belated response. If it works when the table is open, but it doesn't work corectly when it is closed it's most likely due to light reflecting of the surfaces.

I would try to put something like black paper or cardbord on the surfaces between the IR LED and the receiver, both on the bottom and on the top to try and see if that helps.
maybe you can also try to put a little duct-tape in front of he emitting led and punch a hole in it to let less light through...

**Comment by LukeSeinVadder** [comment]
Hi again, 

we solved the problem with 1cm of  shrinking tube over the IR-Emitter , so the signal direction is straight to the IR-LED, and when the ball passes the barrier , it is interupted.

**Comment by swehner** [comment]
Awesome! Yeah, it usually takes a bit of fiddling around with the LED/Receivers. I guess it also depends on how thick the wood is and how it directs the beam.
Glad you got it working!
