### ISSUE TITLE
Don't import libraries for disabled functionality

### ISSUE THREAD

**Issue by swehner** [swehner/foos#9]
If hipchat module is disabled it shouldn't fail fi the dependencies are not found

**Comment by dpaneda** [comment]
I'm not sure about this. While it doesn't makes sense to fail because a dependency of a missing functionality, at a practical level this is not really a problem due to the existence of a tracked dependencies thanks to pip.

Right now, a disabled functionality usually works as a "dry run", doing everything but the actual action. This allows to test features which are usually disabled due to some needed configuration (hipchat) or just because are annoying on testing (sound).

What do you think? As I say, I'm not sure but we should choose an approach.

**Comment by dpaneda** [comment]
Done, by creating a plugin system.
